// <auto-generated />
namespace Tupkach.Bot.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TupkacosMigraciqXd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TupkacosMigraciqXd));
        
        string IMigrationMetadata.Id
        {
            get { return "201804071807590_TupkacosMigraciqXd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
